### ISSUE TITLE
Copied scripts.

### ISSUE THREAD

**Issue by non-reai** [BizmoFunions895/Gimkit-Hacks#3]
Could you like not copy someone else's script???

**Comment by renner875** [comment]
The script is marked as his in the repo three times. I only reposted
this work for my classmates to have easy access to it. My account
combines some of my own work as well as the work of others to put all the
scripts people in my school might need into one place. On top of this, the gimkit script barely even works. Sorry for any
confusion.

**Comment by non-reai** [comment]
what? the script im referring to is literally named "my gimkit hack"??

**Comment by renner875** [comment]
Is it?? Give me a minute I’ll be sure to change that, sorry about that. I
thought I changed it! I’ll get on that immediately!

**Comment by non-reai** [comment]
thanks.
